name: DeployAndReleaseNote
 
on:
 push:
   branches:
     - develop

jobs:
  UpdateReleaseDraft:
    runs-on: Ubuntu-latest
    steps:
      - id: step1
        uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  SteamDeploy:
    runs-on: self-hosted
    steps:
    - name: SteamDeploy
      shell: cmd
      env:
        STEAMSCRIPT: ${{github.workspace}}${{secrets.STEAMSCRIPT}}
      run: |
        "${{secrets.STEAMCMD}}" +login ${{secrets.STEAMUSERNAME}} ${{secrets.STEAMPASSWORD}} +run_app_build ${{env.STEAMSCRIPT}} +quit
          
  DiscordNotify:
    runs-on: ubuntu-latest
    needs: [SteamDeploy, UpdateReleaseDraft]
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{secrets.DISCORD_WEBHOOK}}
