name: DeployAndReleaseNote
 
on:
 push:
   branches:
     - develop

jobs:
  UpdateReleaseDraft:
    runs-on: Ubuntu-latest
    outputs:
     tagname: ${{ steps.step1.outputs.tag_name }}
    steps:
      - id: step1
        uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  SteamDeploy:
    runs-on: self-hosted
    steps:
    - name: SteamDeploy
      shell: cmd
      env:
        STEAMCMD: '"C:\SteamSDK\sdk\tools\ContentBuilder\builder\steamcmd.exe"'
        STEAMUSERNAME: ${{ secrets.STEAMUSERNAME }}
        STEAMPASSWORD: ${{ secrets.STEAMPASSWORD }}
        STEAMSCRIPT: ${{github.workspace}}\BuildScript\Steam\app_build_968770.vdf
      run: |
        ${{env.STEAMCMD}} +login ${{env.STEAMUSERNAME}} ${{env.STEAMPASSWORD}} +run_app_build ${{env.STEAMSCRIPT}} +quit
          
  DiscordNotify:
    runs-on: ubuntu-latest
    needs: [SteamDeploy, UpdateReleaseDraft]
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK}}
