name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
  
  RemoveOldBuilds:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{github.workspace}}/Build
  
  UnityTest:
    runs-on: self-hosted
    needs: [Checkout]
    strategy:
      fail-fast: true    
    steps:
    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile  -  
    
    - name: Unity Editor Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile  -  
      
  Win64Build:
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.Win64Build -logFile -
        
        
        
  NSBuild:
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.SwitchBuild -logFile -

  SteamDeploy:
    needs: [Win64Build, NSBuild, UnityTest]
    runs-on: self-hosted
    steps:
    - name: SteamDeploy
      shell: cmd
      env:
        STEAMCMD: '"C:\SteamSDK\sdk\tools\ContentBuilder\builder\steamcmd.exe"'
        STEAMUSERNAME: ${{ secrets.STEAMUSERNAME }}
        STEAMPASSWORD: ${{ secrets.STEAMPASSWORD }}
        STEAMSCRIPT: ${{github.workspace}}\BuildScript\Steam\app_build_968770.vdf
      run: |
        ${{env.STEAMCMD}} +login ${{env.STEAMUSERNAME}} ${{env.STEAMPASSWORD}} +run_app_build ${{env.STEAMSCRIPT}} +quit

  UpdateReleaseDraft:
    needs: [SteamDeploy]
    runs-on: Ubuntu-latest
    outputs:
      tagname: ${{ steps.step1.outputs.tag_name }}
    steps:
      - id: step1
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  DiscordNotify:
    runs-on: ubuntu-latest
    needs: [SteamDeploy]
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK}}
          
  TagNameDisplay:
      runs-on: self-hosted
      needs: [UpdateReleaseDraft]
      steps:
      - run: echo ${{ needs.UpdateReleaseDraft.outputs.tagname }}
