name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false

    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile  -  
    
    - name: Unity Editor Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile  -  
      

    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.Build -logFile -  

  deploy:
    needs: [build]
    runs-on: self-hosted
    steps:
    - name: SteamDeploy
      shell: cmd
      env:
        STEAMCMD: '"C:\SteamSDK\sdk\tools\ContentBuilder\builder\steamcmd.exe"'
        STEAMUSERNAME: ${{ secrets.STEAMUSERNAME }}
        STEAMPASSWORD: ${{ secrets.STEAMPASSWORD }}
        STEAMSCRIPT: ${{github.workspace}}\BuildScript\Steam\app_build_968770.vdf
      run: |
          ${{env.STEAMCMD}} login ${{env.STEAMUSERNAME}} ${{env.STEAMPASSWORD}} 
          ${{env.STEAMCMD}} run_app_build ${{env.STEAMSCRIPT}}
      
