name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
        path: /BuilderFolder
        

    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe" -projectPath . -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics -logFile - -buildWindows64Player=./BuilderFolder/build/TestProject.exe
    
