# This is a basic workflow to help you get started with Actions

name: CI

env:
  path: C:/
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - name: Clean temp directory
          run: 
            ECHO Building...
            "C:\Program Files\Unity\Editor\Unity.exe" -projectPath "C:\GitRepo\CICDTestProject" -buildTarget 'win64' -batchmode -nographics -quit -buildWindows64Player= "C:\"
            ECHO "Build Completed"
            ECHO "Compressing Build"
