name: PullRequestCheck

on:
  pull_request:
    branches:
      - develop
  
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
  
  RemoveOldBuilds:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{github.workspace}}/Build
  
  UnityTest:
    runs-on: self-hosted
    needs: [Checkout]
    strategy:
      fail-fast: true    
    steps:
    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile  -  
    
    - name: Unity Editor Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile  -  
      
  Win64Build:
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.Win64Build -logFile -
                        
  NSBuild:
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.SwitchBuild -logFile -
          
  DiscordNotify:
    runs-on: ubuntu-latest
    needs: [NSBuild,Win64Build,UnityTest]
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK}}
          

