name: PullRequestCheck

on:
  pull_request:
    branches:
      - develop
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
  
  RemoveOldBuilds:
    needs: [Checkout]
    runs-on: self-hosted
    env:
      BUILD_PATH: /Build
    steps:
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{github.workspace}}${BUILD_PATH}
  
  UnityTest:
    env:  
      UNITY_PATH: C:\Program Files\Unity\Editor\Unity.exe
    needs: [Checkout]    
    runs-on: self-hosted  
    strategy:
      fail-fast: true    
    steps:
    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "${{env.UNITY_PATH}}"  -batchmode -projectPath . -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile  -  
    
    - name: Unity Editor Mode Test
      shell: cmd
      run: |
        "${{env.UNITY_PATH}}"  -batchmode -projectPath . -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile  -                                                  
      
  Win64Build:
    env: 
      UNITY_PATH: C:\Program Files\Unity\Editor\Unity.exe
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "${{env.UNITY_PATH}}"  -quit -batchmode -projectPath .   -buildTarget Win64  -nographics  -executeMethod CI.Win64Build -logFile -
                        
  NSBuild:
    env: 
      UNITY_PATH: C:\Program Files\Unity\Editor\Unity.exe    
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "${{env.UNITY_PATH}}"  -quit -batchmode -projectPath .   -buildTarget Switch  -nographics  -executeMethod CI.SwitchBuild -logFile -          
    
  DiscordNotify_Fail:
    needs: [UnityTest, Win64Build, NSBuild] 
    runs-on: ubuntu-latest     
    if: ${{ failure() || cancelled()}}
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK}}
          status: Failure    
  
  Atomerge:
    needs: [UnityTest, Win64Build, NSBuild]
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_TOKEN }}"
          MERGE_LABELS: ""
          UPDATE_LABELS: ""

          




