name: PullRequestCheck

on:
  pull_request:
    branches:
      - develop
  
jobs:
  Checkout:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        clean: false
  
  RemoveOldBuilds:
    runs-on: self-hosted
    needs: [Checkout]
    steps:
    - name: Remove File
      uses: JesseTG/rm@v1.0.2
      with:
        path: ${{github.workspace}}/Build
  
  UnityTest:
    runs-on: self-hosted
    needs: [Checkout]
    strategy:
      fail-fast: true    
    steps:
    - name: Unity Play Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -batchmode -projectPath=/BuilderFolder -runTests -testPlatform PlayMode -testResults TestResult-PlayMode.xml -logFile  -  
    
    - name: Unity Editor Mode Test
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -batchmode -projectPath=/BuilderFolder -runTests -testPlatform EditMode -testResults TestResult-EditMode.xml -logFile  -                                                  
      
  Win64Build:
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.Win64Build -logFile -
                        
  NSBuild:
    needs: [RemoveOldBuilds, UnityTest]
    runs-on: self-hosted
    steps:
    - name: Unity Build
      shell: cmd
      run: |
        "C:\Program Files\Unity\Editor\Unity.exe"  -quit -batchmode -projectPath=/BuilderFolder   -buildTarget Win64  -nographics  -executeMethod CI.SwitchBuild -logFile -
          
  DiscordNotify:
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled()}}
    needs: [UnityTest, Win64Build, NSBuild]
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK}}
          status: Failure
  
  Atomerge:
    runs-on: ubuntu-latest
    needs: [UnityTest, Win64Build, NSBuild]
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          UPDATE_LABELS: ""
          



