name: Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  deploy:
      runs-on: self-hosted
      steps:
      - name: SteamDeploy
        shell: cmd
        env:
          STEAMCMD: '"C:\SteamSDK\sdk\tools\ContentBuilder\builder\steamcmd.exe"'
          STEAMUSERNAME: ${{ secrets.STEAMUSERNAME }}
          STEAMPASSWORD: ${{ secrets.STEAMPASSWORD }}
          STEAMSCRIPT: ${{github.workspace}}\BuildScript\Steam\app_build_968770.vdf
        run: |
            echo ${{env.STEAMCMD}} login ${{env.STEAMUSERNAME}} ${{env.STEAMPASSWORD}} 
            run_app_build ${{env.STEAMSCRIPT}} 



