# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  UpdateReleaseDraft:
    runs-on: Ubuntu-latest
    steps:
      - id: step1
        uses: release-drafter/release-drafter@v5.12.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  TagNameDisplay:
    runs-on: self-hosted
    needs: [UpdateReleaseDraft]
    steps:
    - run: echo ${{ needs.UpdateReleaseDraft.outputs.tagname }}
